### ISSUE TITLE
Color

### ISSUE THREAD

**Issue by vendforce** [vlevit/notify-send.sh#8]
Is there any way to add color to the text ? 

`notify-send.sh  -t 4000 "<i>Time Now</i>" "<span color='#57dafd' font='26px'><i><b>color text</b></i></span>" >/dev/null 2>&1`

Doesn't seem to work

**Comment by vlevit** [comment]
Hi,

Message rendering is a responsibility of a notification daemon (such as built-in notification daemons of Gnome, KDE etc, or a standalone daemon).  The client (`notify-send.sh`) just sends a message to the standard Desktop Notifcation D-BUS interface.

Support for color and advanced markup is out of scope of Desktop Notifications Specification. That's why probably most implementation don't support advanced markup. Though you might try to find some implementation that support it. Here you can find a list of daemons: https://wiki.archlinux.org/index.php/Desktop_notifications#Standalone

Here is a quote from the spec on markup

> 
> Markup
> 
> Body text may contain markup. The markup is XML-based, and consists of a small subset of HTML along with a few additional tags.
> 
> The following tags should be supported by the notification server. Though it is optional, it is recommended. Notification servers that do not support these tags should filter them out.
> <b> ... </b> 	Bold
> <i> ... </i> 	Italic
> <u> ... </u> 	Underline
> <a href="..."> ... </a> 	Hyperlink
> <img src="..." alt="..."/> 	Image
> 
> A full-blown HTML implementation is not required of this spec, and notifications should never take advantage of tags that are not listed above. As notifications are not a substitute for web browsers or complex dialogs, advanced layout is not necessary, and may in fact limit the number of systems that notification services can run on, due to memory usage and screen space. Such examples are PDAs, certain cell phones, and slow PCs or laptops with little memory.
> 
> For the same reason, a full XML or XHTML implementation using XSLT or CSS stylesheets is not part of this specification. Information that must be presented in a more complex form should use an application-specific dialog, a web browser, or some other display mechanism.
> 
> The tags specified above mark up the content in a way that allows them to be stripped out on some implementations without impacting the actual content.

https://developer.gnome.org/notification-spec/#markup
